### ISSUE TITLE
Bug when loading a new round

### ISSUE THREAD

**Issue by Seniru** [a801-luadev/cannonup#1]
This issue is related with cannonup module and  doesn't occurs all the time. I think this is a problem with a map

## Steps to reproduce
 - Play as usual
 - Win a round
 - This bug won't appear all the time as I mentioned earlier. So you have to pass multiple rounds to get this issue

## Expected
 - Stopping of spawning of cannons
 - A new round starts as normal

## Actual
 - Prints somebody won
 - Starts the countdown for the next map
 - Cannons keep spawning
 - New round won't start and keeps counting for the next map continuously

*I hope this could be fixed quickly as all of the mice have to get away from the room to fix this by themselves*

Related: https://github.com/Lautenschlager-id/Transformice/issues/1

**Comment by Lautenschlager-id** [comment]
Hm, it's actually impossible to happen with the current code :thinking: 

This is some pseudocode of the current eventLoop behavior:
```
if time2newmap > 0
	if --time2newmap <= 0
		newGame()
	return

if nomoretime or countalive < 2
	winner()
	time2newmap = 3
else
	cannon()
```

It's impossible to start the countdown for the next map while cannons are being summoned :thinking: 

That said, a GIF would be very appreciated

**Comment by Seniru** [comment]
I'll try
But I have no idea how to make a GIF :disappointed:

**Comment by Lautenschlager-id** [comment]
There are many tools for it, it can be a video too. Try bandicam. It's free.

**Comment by Seniru** [comment]
OK 👍
I'll send tomorrow

**Comment by Seniru** [comment]
OK! Finally I got a chance to get that bug again.

The GIF has no complete evidence. But this is the thing I said

![Infinitely loading map](https://im6.ezgif.com/tmp/ezgif-6-31ea631cd896.gif)

This is what happened before taking this video

- A guest, afk souris of myself and me was playing
- 2 souris dead
- I was the only player left but the cannons keep summoning
- I suicided
- Cannons still keep summoning
- The guest left
- It printed 'King_seniru#5890 is the winner' and started countdown for next map
- Map didn't load and it keep counting down

I'll try to capture a full video next time

**Comment by Seniru** [comment]
Another instance

![another example](https://im6.ezgif.com/tmp/ezgif-6-78786bb788d7.gif)

**Comment by Seniru** [comment]
Here's what happened finally after everybody went

![image](https://user-images.githubusercontent.com/34127015/67138225-cb684780-f25d-11e9-880d-fb30b010e098.png)

It says ' King_seniru won!' even I'm dead

**Comment by Lautenschlager-id** [comment]
I've edited some stuff in the code, maybe that was the problem. At least it's more efficient now. Let me know if it still happens.

**Comment by Seniru** [comment]
OK 👍
